[package]
name = "poly-clob-rs"
version = "0.1.0"
edition = "2021"
authors = ["Florent <FlorentG74@proton.me>"]
description = "A Rust client library for the Polymarket CLOB (Central Limit Order Book) API"
license = "MIT OR Apache-2.0"
repository = "https://github.com/FlorentG74/poly-clob-rs"
homepage = "https://github.com/FlorentG74/poly-clob-rs"
documentation = "https://docs.rs/poly-clob-rs"
readme = "README.md"
keywords = ["polymarket", "prediction-markets", "clob", "api", "blockchain"]
categories = ["api-bindings", "web-programming::http-client", "cryptography::cryptocurrencies"]

[dependencies]
serde = { version = "^1.0", default-features = false, features = ["derive"] }
reqwest = { version = "0.12.28", features = ["default-tls", "json"] }
futures = { version = "0.3" }
serde_json = "1.0"
tokio = { version = "1.48.0",  default-features = false, features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
hex = { version = "0.4.3" }
chrono = { version = "0.4.42", features = ["serde"] }
sha2 = { version = "0.10.9" }
hmac = "0.12.1"
base64 = { version = "0.22.1" }
strum_macros = "0.27.2"
typed-builder = "0.23"
alloy = { version = "1.2.1", features = ["dyn-abi", "signer-local"] }
log = "0.4.29"
anyhow = "1.0"
rust_decimal = { version = "1.39", features = ["serde"] }
diesel = { version = "2.3.5", features = ["postgres"], optional = true }

[features]
default = []
with-diesel = ["diesel"]

# [package.metadata.cargo-machete]
# ignored = ["strum"]
